### ISSUE TITLE
[JRELEASER] Remove explicit changelog format 

### ISSUE THREAD

**Issue by aalmiray** [cbmarcum/skeletal#38]
Since JReleaser 1.4.0, when using the `conventional-commits` preset there's no need for explicit format, that is

https://github.com/cbmarcum/skeletal/blob/5d08fb9ceaf49ad428f641b4bad730e424bc145f/jreleaser.yml#L25-L26

Line 25 can be removed.

**Comment by cbmarcum** [comment]
Hi @aalmiray . Thanks for letting me know!
And thanks for great tool!
Best regards
